server:
  port: 8000

database:
  host: "119.91.239.178"    # 数据库主机
  port: 3306           # 数据库端口
  name: "todo_list"    # 数据库名称
  user: "todo_list"         # 数据库用户名
  password: "nyGdHZxyrnm6h8M3"   # 数据库密码