spring:
  application:
    name: spring-todo-list
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chuxin.springtodolist.controller

knife4j:
  enable: true
  setting:
    language: zh_cn